### ISSUE TITLE
latest jenv not compatible with latest IDEA

### ISSUE THREAD

**Issue by nauni77** [madplay/Mad-jEnv#21]
hello, 
for latest plugins you defined a range of valid IDEA installation "2017.2-2019.1.4" - that means with 2019.2 it is not compatible. Older versions you defined "2019.1+" - this is compatible with 2019.2. I don't think this is wanted - but I didn't have a look at the code.

At the moment at intelliJ the version 0.0.2 is available and installed, but not the latest version 0.1.1. Normally the latest version is more compatible with later IDEA versions.

Maybe you can have a look at this. Because jenv is a really nice tool and it would be great to have support at IntelliJ! :-)

Thanks and best regards, Oli

**Comment by nauni77** [comment]
Screenshot of you latest releases: 

![Bildschirmfoto 2019-10-18 um 17 11 15](https://user-images.githubusercontent.com/39400842/67106514-138a5a00-f1cb-11e9-8e39-59882b354636.png)

**Comment by madplay** [comment]
Hello, I modified the plugin to work with the 2019.2 version.
However, we have to wait for JetBrain's plugin review.
https://plugins.jetbrains.com/plugin/12761-mad-jenv

If the review passes, I will close the issue after checking that it is working properly.

Thank you for your good feedback :D

**Comment by madplay** [comment]
Hello, I modified the plugin to work with the 2019.2 version.
However, we have to wait for JetBrain's plugin review.
https://plugins.jetbrains.com/plugin/12761-mad-jenv

I will close the issue after checking that the review passed and working properly.

Thank you for your good feedback :D

**Comment by madplay** [comment]
The update has been approved. Thanks!

**Comment by nauni77** [comment]
Hello, 
thanks for your fix. Now IntelliJ install the latest version of this plugin! :-)

Best regards, Oli
