### ISSUE TITLE
Not compatible with IntelliJ 2019.3

### ISSUE THREAD

**Issue by leggiero** [madplay/Mad-jEnv#24]
Hi,

Thanks for proving the plugin.
I'd like to report that the release 0.1.2 is not compatible with IntelliJ 2019.3.

From `IntelliJ > Preferences > Plugins`:
![image](https://user-images.githubusercontent.com/873672/70350629-fc78f780-185e-11ea-87b7-75591d286d7d.png)

Thank you,

Eduardo Leggiero

**Comment by madplay** [comment]
It was solved through the following issue (https://github.com/madplay/Mad-jEnv/issues/25)
