### ISSUE TITLE
Plugin incompatible with InteliJ IDEA 2019.3.3

### ISSUE THREAD

**Issue by bc-ibanez** [madplay/Mad-jEnv#25]
I would like to bring to attention that the plugin has been marked as incompatible with [InteliJ IDEA 2019.3.3](https://confluence.jetbrains.com/display/IDEADEV/IntelliJ+IDEA+2019.3.3+(193.6494.35+build)+Release+Notes?utm_source=product&utm_medium=link&utm_campaign=IU&utm_content=2019.2) according to the update pop-up of InteliJ when trying to update.

**Comment by madplay** [comment]
Hello! The code has been modified but now I am waiting for JetBrains's plugin review.
https://plugins.jetbrains.com/plugin/12761-mad-jenv/update/80458

I will close the issue after the review passed and working properly.

Thank you for waiting. I'm tied up these days :(

**Comment by madplay** [comment]
The update has been approved. Thanks!
