### ISSUE TITLE
Always creates .java-version file

### ISSUE THREAD

**Issue by jcassee** [madplay/Mad-jEnv#44]
The plugin always creates a .java-version file, even if the intention is to use the system Java version (although, why use this plugin then?) or, more likely, it's not a Java project. As a work-around I now remove the file every time.

Is it possible to revert this behavior?

**Comment by madplay** [comment]
Removed the method to create a .java-version file.
I'm thinking about another way to improve it.

Sorry for the inconvenience. :(

**Comment by jcassee** [comment]
Thank you, that was quick!

**Comment by madplay** [comment]
I requested the update and it will be approved within 2 days :)

**Comment by jcassee** [comment]
Weirdly, my IntelliJ instance still wants to install 1.2.
